package com.init.mybatis_6.bean;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_department.id
     *
     * @mbggenerated Tue Aug 27 11:54:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_department.dept_name
     *
     * @mbggenerated Tue Aug 27 11:54:00 CST 2019
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_department.id
     *
     * @return the value of tbl_department.id
     * @mbggenerated Tue Aug 27 11:54:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_department.id
     *
     * @param id the value for tbl_department.id
     * @mbggenerated Tue Aug 27 11:54:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_department.dept_name
     *
     * @return the value of tbl_department.dept_name
     * @mbggenerated Tue Aug 27 11:54:00 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_department.dept_name
     *
     * @param deptName the value for tbl_department.dept_name
     * @mbggenerated Tue Aug 27 11:54:00 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}